version: "3.8"
services:
  postgresidp:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: nestjsbase
    volumes:
      - ./db:/var/lib/postgres
    ports:
      - "9432:5432"
    restart: unless-stopped
    networks:
      - intranet_hydra

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
    networks:
      - intranet_hydra

volumes:
  pgadmin:

networks:
  intranet_hydra:
    driver: bridge

# explore inside main docker
# docker exec -t -i main ls -lrt /home/node
